```{r}
control <- c(12, 17, 14, 9)
drug <- c(23, 18, 26, 21)

diff.mean <- mean(control) - mean(drug)

library(gtools)

Z <- c(control, drug)

perm <- combinations(8,4)

diff.perm <- numeric(nrow(perm))

for(i in 1:nrow(perm)){
	diff.perm[i] <- mean(Z[perm[i, ]]) - mean(Z[-perm[i, ]]) 
}

asl <- mean(abs(diff.perm) >= abs(diff.mean))

```

```{r}
library(ggplot2)

ggplot(data.frame(diff.perm)) +
	geom_histogram(mapping = aes(x = diff.perm, y = stat(density)), color = "white", binwidth = 0.5) +
	geom_vline(xintercept = diff.mean, color = "blue") +
	geom_vline(xintercept = -diff.mean, color = "blue")
```

```{r}
factorial(71) / (factorial(12)^3 * factorial(10) * factorial(11) * factorial(14))
```

```{r}
# for the F statistics we basicaly have our sample weight VALUES gouped in different GROUPS according to diet
# thus for aov that computes the F statistcs we specify both as the aov(VALUES ~ GROUP) 
aov.chicks <- aov(chickwts$weight ~ chickwts$feed)
summary(aov.chicks)

library(broom)
# tidy enables us to see the names of various values given in a test
tidy(aov.chicks)
```

```{r}
set.seed(102)
nreps <- 1000

rep.f.stat <- replicate(nreps, {
	group_sample <- sample(chickwts$feed)
	aov_rep <- aov(chickwts$weight ~ group_sample)
	tidy(aov_rep)$statistic[1]
})
```

```{r}
library(ggplot2)

ggplot(data.frame(rep.f.stat), aes(x = rep.f.stat)) +
	geom_histogram(aes(y = stat(density)), color = "white", binwidth = 0.2) +
	geom_density(aes(y = stat(density)))
```

```{r}
(f.stat <- summary(aov.chicks)[[1]][1, "F value"])
# calculate how many of the samples results have value greater than the given one
# get the probability (p-value) by dividing with the number of samples
(p.val.approx <- sum(abs(rep.f.stat) > abs(f.stat)) / nreps)
```

```{r}
weight.soybean <- chickwts$weight[chickwts$feed == "soybean"]
weight.linseed <- chickwts$weight[chickwts$feed == "linseed"]
ecdf.soy <- ecdf(weight.soybean)
ecdf.linseed <- ecdf(weight.linseed)

# find the maximum difference between the two ecdfs
# no duplicate elements with unique
weights <- sort(unique(c(weight.soybean, weight.linseed)))
ecdf.diffs <- abs(ecdf.soy(weights) - ecdf.linseed(weights))
max(ecdf.diffs)
```

